### ISSUE TITLE
Async issue

### ISSUE THREAD

**Issue by pabb85** [tomasbedrich/hikconnect#2]
Hi there - great project and thank you for writing it.

I have an issue when trying to run the demo code from the readme of "SyntaxError: 'async with' outside async function" for line 3.  This is on Python 3.10.4

Thank you,
Paul

**Comment by tomasbedrich** [comment]
Thanks. :)

You are right, the example in README is incomplete. You need to wrap your code into async function like this: https://docs.python.org/3/library/asyncio-task.html#toc-entry-1

**Comment by pabb85** [comment]
Thank you!
