### ISSUE TITLE
How can get more api?

### ISSUE THREAD

**Issue by minhsu12113** [tomasbedrich/hikconnect#3]
Hey Tomas, how can i get more api from Hik-Connect, where is document bro? I want to download videos from recorder.

**Comment by tomasbedrich** [comment]
I am not aware of any API documentation. THe current functionality has been reverse engineered. If you find some, please provide it.

**Comment by minhsu12113** [comment]
> I am not aware of any API documentation. THe current functionality has been reverse engineered. If you find some, please provide it.

How can you reverse engineered it bro? From source code http://opensource.hikvision.com/ right?

**Comment by tomasbedrich** [comment]
From running Android application in controlled environment (recording its HTTP calls).

**Comment by minhsu12113** [comment]
> From running Android application in controlled environment (recording its HTTP calls).

Thanks bro
