### ISSUE TITLE
Help HTTP request

### ISSUE THREAD

**Issue by ur5zeb** [tomasbedrich/hikconnect#6]
`def getStatusAXPro(serial):
    apiData = f'POST%20%2FISAPI%2FSecurityCP%2Fstatus%2Fhost%3Fformat%3Djson%20HTTP%2F1.1%0D%0AAuthorization%3A%20Digest%20username%3D%22ur5zeb%22%2C%20nonce%3D%226939f56cfbc71338dc2b403439a0eff7%3A1544623276710%22%2C%20response%3D%223a6ba1ddf68fdee013955baca667e7fb%22%2C%20UserType%3D%22Operator%22%0D%0AUserType%3A%20Operator%0D%0A%0D%0A%7B%22AlarmHostStatusCond%22%3A%7B%22averageNoise%22%3Afalse%2C%22battery%22%3Atrue%2C%22batteryNo%22%3A%5B1%5D%2C%22communiStatus%22%3Atrue%2C%22hostStatus%22%3Atrue%2C%22subSys%22%3Atrue%7D%7D'
    payload=(f"deviceSerial={serial}&apiKey={apiKey}&apiData={apiData}")
    conn = http.client.HTTPSConnection("apiieu.hik-connect.com")
    conn.request("POST", "/v3/userdevices/v1/isapi/", payload, headers)
    res = conn.getresponse()
    data = res.read().decode("utf-8")
    data = json.loads(data)
    #data = data
    return data['HostStatus']`Hello Help me write a more correct AXPRO state function
   I can't understand the apiDate parameter

**Comment by tomasbedrich** [comment]
Hello, this is a Python library to communicate with Hikvision smart doorbells via Hik-Connect cloud. There are no plans to support AX PRO alarms. Even if I want, given the information above I really cannot help.
